# Generated by Django 2.1.5 on 2020-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phase_week_target_is_excluded_from_wt_mp_assignment_cause',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='phase_week_target_is_excluded_from_wt_mp_assignment_wish',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
