# Generated by Django 2.1.5 on 2020-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201129_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='workpackage_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
