# Generated by Django 2.1.5 on 2020-12-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_workpackage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='workpackage_title',
        ),
    ]
