# Generated by Django 2.1.5 on 2020-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_book_workpackage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='workpackage_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
