# Generated by Django 2.1.5 on 2020-12-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_workpackage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_calendar',
            options={'ordering': ['datetime_start']},
        ),
    ]
