# Generated by Django 2.1.5 on 2020-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201205_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id_asinteger',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
