# Generated by Django 2.1.5 on 2020-12-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201206_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memorization_Package_MP_Technique_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(default='', max_length=255)),
                ('t_memorization_package_memory_palace_or_cards_technique_fk6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Or_Cards_Technique')),
            ],
            options={
                'db_table': 't_memorization_package_mp_technique_category',
                'ordering': ['category_title'],
            },
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='t_memorization_package_memory_palace_or_cards_technique_fk2',
        ),
        migrations.AddField(
            model_name='book',
            name='is_included_in_memorization_package_creation',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_separate_memory_palace',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='is_included_in_memorization_package_creation',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='t_memorization_package_mp_technique_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_MP_Technique_Category'),
        ),
    ]
