# Generated by Django 2.1.5 on 2020-12-07 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201207_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_memorization_package_mp_technique_category',
            name='t_memorization_package_memory_palace_or_cards_technique_fk6',
        ),
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='t_memorization_package_mp_technique_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_MP_Technique_Category'),
        ),
    ]
