# Generated by Django 2.1.5 on 2020-12-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201207_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_memorization_package_memory_palace_or_cards_technique',
            options={'ordering': ['created_datetime']},
        ),
    ]
