# Generated by Django 2.1.5 on 2020-12-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201208_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='t_memory_palace_type_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type_Location'),
        ),
    ]
