# Generated by Django 2.1.5 on 2020-12-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_bookinstance_t_memory_palace_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memorization_Package_MP_Technique_Assignmenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type_description', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 't_memorization_package_mp_technique_assignmenttype',
                'ordering': ['assignment_type_description'],
            },
        ),
        migrations.CreateModel(
            name='T_Memorization_Package_MP_Technique_Assignmenttype_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(default='', max_length=255)),
                ('t_memorization_package_mp_technique_assignmenttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_MP_Technique_Assignmenttype')),
            ],
            options={
                'db_table': 't_memorization_package_mp_technique_assignmenttype_category',
                'ordering': ['category_title'],
            },
        ),
        migrations.RemoveField(
            model_name='author',
            name='t_memorization_package_mp_technique_category',
        ),
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='t_memorization_package_mp_technique_category',
        ),
        migrations.DeleteModel(
            name='T_Memorization_Package_MP_Technique_Category',
        ),
        migrations.AddField(
            model_name='author',
            name='t_memorization_package_mp_technique_assignmenttype_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_MP_Technique_Assignmenttype_Category'),
        ),
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='t_memorization_package_mp_technique_assignmenttype_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_MP_Technique_Assignmenttype_Category'),
        ),
    ]
