# Generated by Django 2.1.5 on 2020-12-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201210_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='t_memory_palace_type_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type_Location'),
        ),
    ]
