# Generated by Django 2.1.5 on 2020-12-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_author_t_memory_palace_type_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_memorization_package_mp_technique_assignmenttype_category',
            name='t_memorization_package_mp_technique_assignmenttype',
        ),
        migrations.DeleteModel(
            name='T_Memorization_Package_MP_Technique_Assignmenttype',
        ),
    ]
