# Generated by Django 2.1.5 on 2020-12-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20201216_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_included_in_memorization_package_creation',
            new_name='is_excluded_from_memorization',
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='is_included_in_memorization_package_creation',
            new_name='is_excluded_from_memorization',
        ),
    ]
