# Generated by Django 2.1.5 on 2020-10-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20181028_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='week_target_comment',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='book',
            name='week_target_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
