# Generated by Django 2.1.5 on 2020-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20201009_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='memorizable_week_target',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
