# Generated by Django 2.1.5 on 2020-11-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_author_memorizable_week_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='week_target_comment',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
