# Generated by Django 2.1.5 on 2020-11-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20201112_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='week_target_description',
            new_name='associated_email_received_account',
        ),
    ]
