# Generated by Django 2.1.5 on 2020-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20201113_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hyperlink_for_readiness_enhancement',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
