# Generated by Django 2.1.5 on 2020-11-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_book_is_shown_at_next_time_measurement_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_shown_at_next_time_measurement_stop',
            field=models.IntegerField(null=True, default=None, max_length=19),
        ),
    ]
