# Generated by Django 2.1.5 on 2020-11-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20201113_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_shown_at_next_time_measurement_stop',
        ),
    ]
