# Generated by Django 2.1.5 on 2020-11-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_book_associated_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_shown_at_next_time_measurement_stop',
            field=models.IntegerField(default=None, max_length=19, null=True),
        ),
    ]
