# Generated by Django 2.1.5 on 2020-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_book_is_shown_at_next_time_measurement_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='plan_duration_mins',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
