# Generated by Django 2.1.5 on 2020-11-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_book_plan_duration_mins'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
