# Generated by Django 2.1.5 on 2020-11-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_book_due_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='due_datetime',
        ),
    ]
