# Generated by Django 2.1.5 on 2020-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_remove_book_due_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
