# Generated by Django 2.1.5 on 2020-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_book_due_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datetime_is_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
