# Generated by Django 2.1.5 on 2020-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_book_datetime_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='associated_email_received_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
