# Generated by Django 2.1.5 on 2020-11-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_book_associated_email_received_datetime'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='t_workpackage',
        ),
    ]
