# Generated by Django 2.1.5 on 2020-11-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20201113_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_frame_from_weekday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
