# Generated by Django 2.1.5 on 2020-11-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_author_date_frame_from_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_frame_to_weekday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
