# Generated by Django 2.1.5 on 2020-11-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_author_date_frame_to_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phase_week_target_is_excluded_from_wt_mp_assignment_cause',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='phase_week_target_is_excluded_from_wt_mp_assignment_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='phase_week_target_is_excluded_from_wt_mp_assignment_wish',
            field=models.CharField(default='', max_length=255),
        ),
    ]
