# Generated by Django 2.1.5 on 2020-11-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20201113_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_done_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_not_during_working_hours',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='memorization_sequence',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='memorization_sequence_is_fixed_because_memorized',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='recurrence_period_weeks',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='week_target_manual_sorting_category_indistinguishable',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='workpackages_relevantinformation_is_separate_memory_palace',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
