# Generated by Django 2.1.5 on 2020-11-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20201114_0853'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinstance',
            table='t_week_target',
        ),
    ]
