# Generated by Django 2.1.5 on 2020-11-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_auto_20201114_0859'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinstance',
            table='t_workpackage_relevantinformation_tobememorized',
        ),
    ]
