# Generated by Django 2.1.5 on 2020-11-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20201114_0902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='t_week_target',
        ),
    ]
