# Generated by Django 2.1.5 on 2020-11-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20201114_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Information_Item_Tobeoperationalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('target_group_question', models.CharField(default='', max_length=1000)),
                ('memorizable_information_item_tobeoperationalized', models.CharField(default='', max_length=1000)),
                ('memorization_sequence_memory_cards_technique', models.IntegerField(default=None, null=True)),
                ('memorization_sequence_memory_palace_technique', models.IntegerField(default=None, null=True)),
                ('memorization_sequence_mem_pal_tec_is_fixed_because_memorized', models.IntegerField(default=None, null=True)),
                ('is_information_item_tobeoperationalized', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 't_information_item_tobeoperationalized',
            },
        ),
    ]
