# Generated by Django 2.1.5 on 2020-11-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_t_information_item_tobeoperationalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('datetime_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('subject_description', models.CharField(default='', max_length=1000)),
                ('location_description', models.CharField(default='', max_length=1000)),
                ('series_frequency_in_days', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
