# Generated by Django 2.1.5 on 2020-11-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_t_calendar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t_calendar',
            table='t_calendar',
        ),
    ]
