# Generated by Django 2.1.5 on 2020-11-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20201114_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_conflict_konfliktgegenstand_titel', models.CharField(default='', max_length=255)),
                ('general_conflict_konfliktgegenstand_mein_ziel_description', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_conflict',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='is_shown_at_next_time_measurement_stop',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_conflict',
            name='priorization_conflict_workpackage_id_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book'),
        ),
    ]
