# Generated by Django 2.1.5 on 2020-11-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_auto_20201114_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memorization_Package_Memory_Palace_Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('memorization_package_title', models.CharField(default='', max_length=255)),
                ('memorization_package_is_active', models.IntegerField(default=None, null=True)),
                ('t_calendar_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar')),
                ('t_information_item_tobeoperationalized_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized')),
                ('t_week_target_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('t_workpackage_relevantinformation_tobememorized_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance')),
            ],
            options={
                'db_table': 't_memorization_package_memory_palace_technique',
            },
        ),
    ]
