# Generated by Django 2.1.5 on 2020-11-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_t_memorization_package_memory_palace_technique'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memorization_Package_Memory_Cards_Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('memorization_package_title', models.CharField(default='', max_length=255)),
                ('memorization_package_is_active', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 't_memorization_package_memory_cards_technique',
            },
        ),
    ]
