# Generated by Django 2.1.5 on 2020-11-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_t_memorization_package_memory_cards_technique'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memory_Palace_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_palace_type', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_memory_palace_type',
            },
        ),
    ]
