# Generated by Django 2.1.5 on 2020-11-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_t_memory_palace_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memory_Palace_Type_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_proposed_for_new_memorization_package', models.IntegerField(default=None, null=True)),
                ('memory_palace_type_location', models.CharField(default='', max_length=255)),
                ('memory_palace_type_location_is_inactive', models.IntegerField(default=None, null=True)),
                ('t_memorization_package_memory_palace_technique_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Technique')),
                ('t_memory_palace_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type')),
            ],
            options={
                'db_table': 't_memory_palace_type_location',
            },
        ),
    ]
