# Generated by Django 2.1.5 on 2020-11-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_t_memory_palace_type_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memory_Palace_Type_Location_Packageassignment_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_to_memorization_package_datetime', models.DateTimeField(blank=True, null=True)),
                ('t_memorization_package_memory_palace_technique_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Technique')),
                ('t_memory_palace_type_location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type_Location')),
            ],
            options={
                'db_table': 't_memory_palace_type_location_packageassignment_timeseries',
            },
        ),
    ]
