# Generated by Django 2.1.5 on 2020-11-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_t_memory_palace_type_location_packageassignment_timeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memory_Palace_Type_Location_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_palace_number', models.IntegerField(default=None, null=True)),
                ('memory_palace_datapoint_description', models.CharField(default='', max_length=255)),
                ('memory_palace_datapoint_lastuse_date', models.DateTimeField(blank=True, null=True)),
                ('memory_palace_datapoint_is_inactive', models.IntegerField(default=None, null=True)),
                ('t_memory_palace_type_location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type_Location')),
            ],
            options={
                'db_table': 't_memory_palace_type_location_number',
            },
        ),
    ]
