# Generated by Django 2.1.5 on 2020-11-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_t_memory_palace_type_location_daytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Calendar_Conflict_Related_Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothetic_appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('hypothetic_appointment_association_description', models.CharField(default='', max_length=255)),
                ('t_calendar_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar')),
                ('t_conflict_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Conflict')),
                ('t_memorization_package_memory_palace_technique_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Technique')),
            ],
            options={
                'db_table': 't_calendar_conflict_related_association',
            },
        ),
    ]
