# Generated by Django 2.1.5 on 2020-11-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_t_calendar_conflict_related_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_calendar_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar'),
        ),
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_information_item_tobeoperationalized_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized'),
        ),
    ]
