# Generated by Django 2.1.5 on 2020-11-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_auto_20201115_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Ausatemmuskulatur_Isnot_Entspannt_Dueto_Strategyrefinemt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('memorized_unit_is_gone_through_mentally', models.IntegerField(default=None, null=True)),
                ('memory_palace_is_enhanced_or_complete', models.IntegerField(default=None, null=True)),
                ('t_calendar_conflict_related_association_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar_Conflict_Related_Association')),
                ('t_conflict_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Conflict')),
            ],
            options={
                'db_table': 't_ausatemmuskulatur_isnot_entspannt_dueto_strategyrefinemt',
            },
        ),
    ]
