# Generated by Django 2.1.5 on 2020-11-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_t_ausatemmuskulatur_isnot_entspannt_dueto_strategyrefinemt'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Ausatemmuskulatur_Strategyrefinement_Conflict_Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_phase_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_ausatemmuskulatur_strategyrefinement_conflict_phase',
            },
        ),
    ]
