# Generated by Django 2.1.5 on 2020-11-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_t_conflict_strategy_category_t_conflict_strategy_category_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_category_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_table_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_category_table',
            },
        ),
        migrations.CreateModel(
            name='t_category_table_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=255)),
                ('t_category_table_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.t_category_table')),
            ],
            options={
                'db_table': 't_category_table_entry',
            },
        ),
        migrations.CreateModel(
            name='T_Category_Table_Predicate_Asverb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate_asverb', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_category_table_predicate_asverb',
            },
        ),
        migrations.CreateModel(
            name='T_Information_Item_Tobeoperationalized_Memor_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_datetime', models.DateTimeField(blank=True, null=True)),
                ('t_information_item_tobeoperationalized_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized')),
            ],
            options={
                'db_table': 't_information_item_tobeoperationalized_memor_timeseries',
            },
        ),
        migrations.CreateModel(
            name='T_Information_Item_Tobeoperationalized_Memor_Timeseries_Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_information_item_tobeoperationalized_memor_timeseries_act',
            },
        ),
    ]
