# Generated by Django 2.1.5 on 2020-11-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_t_category_table_t_category_table_entry_t_category_table_predicate_asverb_t_information_item_tobeope'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_category_table_predicate_asverb',
            name='t_category_table_id_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.t_category_table'),
        ),
    ]
