# Generated by Django 2.1.5 on 2020-11-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_t_category_table_predicate_asverb_t_category_table_id_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Day_Target_Sequence_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_proposed_for_day_target_memory_palace', models.IntegerField(default=None, null=True)),
                ('sequence_memorized_in_day_target_memory_palace', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 't_day_target_sequence_timeseries',
            },
        ),
        migrations.CreateModel(
            name='T_Memory_Palace_Memorization_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_datetime', models.DateTimeField(blank=True, null=True)),
                ('t_conflict_strategy_category_measure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Conflict_Strategy_Category_Measure')),
                ('t_information_item_tobeoperationalized_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized')),
                ('t_week_target_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('t_workpackage_relevantinformation_tobememorized_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance')),
            ],
            options={
                'db_table': 't_memory_palace_memorization_timeseries',
            },
        ),
        migrations.CreateModel(
            name='T_Memory_Palace_Memorization_Timeseries_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_memory_palace_memorization_timeseries_action',
            },
        ),
        migrations.CreateModel(
            name='T_Week_Target_Is_Excluded_From_Dt_Mp_Assignment_On_Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_target_isnot_potential_day_target_on_weekday_date', models.DateField(blank=True, null=True)),
                ('t_week_target_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
            options={
                'db_table': 't_week_target_is_excluded_from_dt_mp_assignment_on_weekday',
            },
        ),
    ]
