# Generated by Django 2.1.5 on 2020-11-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_t_day_target_sequence_timeseries_t_memory_palace_memorization_timeseries_t_memory_palace_memorizatio'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Workpackage_Actual_Duration_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_datetime', models.DateTimeField(blank=True, null=True)),
                ('measurement_type_start_or_stop', models.CharField(default='', max_length=255)),
                ('t_workpackage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
            options={
                'db_table': 't_workpackage_actual_duration_timeseries',
            },
        ),
    ]
