# Generated by Django 2.1.5 on 2020-11-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0069_t_workpackage_actual_duration_timeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Wt_Or_Wp_Or_Infotbo_Category_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('t_category_table_entry_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table_Entry')),
                ('t_category_table_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.t_category_table')),
                ('t_information_item_tobeoperationalized_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized')),
                ('t_week_target_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('t_workpackage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
            options={
                'db_table': 't_wt_or_wp_or_infotbo_category_timeseries',
            },
        ),
    ]
