# Generated by Django 2.1.5 on 2020-11-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20201115_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_category_table_entry',
            options={},
        ),
    ]
