# Generated by Django 2.1.5 on 2020-11-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_auto_20201115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            name='t_category_table_entry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table_Entry'),
        ),
    ]
