# Generated by Django 2.1.5 on 2020-11-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_auto_20201115_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_category_table_entry',
            options={'verbose_name': 'T_Category_Table_Entry'},
        ),
    ]
