# Generated by Django 2.1.5 on 2020-11-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_auto_20201115_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Week_Target_Or_Workpackage_Or_Relevinf_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_datetime', models.DateTimeField(blank=True, null=True)),
                ('action_description_create_read_update_delete', models.CharField(default='', max_length=255)),
                ('t_week_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('t_workpackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
                ('t_workpackage_relevantinformation_tobememorized', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance')),
            ],
            options={
                'db_table': 't_week_target_or_workpackage_or_relevinf_timeseries',
            },
        ),
    ]
