# Generated by Django 2.1.5 on 2020-11-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_t_week_target_or_workpackage_or_relevinf_timeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='t_memorization_package_memory_palace_technique_foreignkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Technique'),
        ),
        migrations.AddField(
            model_name='author',
            name='t_memory_palace_type_location_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type_Location_Number'),
        ),
    ]
