# Generated by Django 2.1.5 on 2020-11-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0081_auto_20201115_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='t_calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar'),
        ),
    ]
