# Generated by Django 2.1.5 on 2020-11-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_auto_20201115_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_information_item_tobeoperationalized_memor_timeseries',
            name='t_information_item_tobeoperationalized_memor_timeseries_act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized_Memor_Timeseries_Act'),
        ),
    ]
