# Generated by Django 2.1.5 on 2020-11-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_t_information_item_tobeoperationalized_memor_timeseries_t_information_item_tobeoperationalized_memor'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_category_table_predicate_asverb',
            name='t_category_table_id_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='T_Category_Table_Related_Name', to='catalog.t_category_table'),
        ),
    ]
