# Generated by Django 2.1.5 on 2020-11-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_t_category_table_predicate_asverb_t_category_table_id_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_calendar',
            name='t_calendar_conflict_related_association_foreignkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar_Conflict_Related_Association'),
        ),
        migrations.AddField(
            model_name='t_calendar',
            name='t_memorization_package_memory_palace_technique_foreignkey4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Technique'),
        ),
        migrations.AddField(
            model_name='t_calendar',
            name='t_memory_palace_type_location_daytime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type_Location_Daytime'),
        ),
        migrations.AddField(
            model_name='t_calendar',
            name='t_workpackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Book_Related_Name', to='catalog.Book'),
        ),
    ]
