# Generated by Django 2.1.5 on 2020-11-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_auto_20201115_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_conflict',
            name='priorization_conflict_workpackage_id_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Book_Related_Name2', to='catalog.Book'),
        ),
    ]
