# Generated by Django 2.1.5 on 2020-11-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0091_auto_20201115_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_memory_palace_memorization_timeseries',
            old_name='t_week_target_id',
            new_name='t_week_target',
        ),
    ]
