# Generated by Django 2.1.5 on 2020-11-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0092_auto_20201116_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_memory_palace_memorization_timeseries',
            old_name='t_conflict_strategy_category_measure_id',
            new_name='t_conflict_strategy_category_measure',
        ),
        migrations.RenameField(
            model_name='t_memory_palace_memorization_timeseries',
            old_name='t_information_item_tobeoperationalized_id',
            new_name='t_information_item_tobeoperationalized',
        ),
        migrations.RenameField(
            model_name='t_memory_palace_memorization_timeseries',
            old_name='t_workpackage_relevantinformation_tobememorized_id',
            new_name='t_workpackage_relevantinformation_tobememorized',
        ),
    ]
