# Generated by Django 2.1.5 on 2020-11-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0093_auto_20201116_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_week_target_is_excluded_from_dt_mp_assignment_on_weekday',
            old_name='t_week_target_id',
            new_name='t_week_target',
        ),
        migrations.RenameField(
            model_name='t_workpackage_actual_duration_timeseries',
            old_name='t_workpackage_id',
            new_name='t_workpackage',
        ),
    ]
