# Generated by Django 2.1.5 on 2020-11-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_auto_20201116_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            old_name='t_category_table_id',
            new_name='t_category_table',
        ),
        migrations.RenameField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            old_name='t_information_item_tobeoperationalized_id',
            new_name='t_information_item_tobeoperationalized',
        ),
        migrations.RenameField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            old_name='t_week_target_id',
            new_name='t_week_target',
        ),
        migrations.RenameField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            old_name='t_workpackage_id',
            new_name='t_workpackage',
        ),
        migrations.RemoveField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            name='t_category_table_entry_id',
        ),
        migrations.AddField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            name='t_category_table_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.t_category_table_entry'),
        ),
    ]
