# Generated by Django 2.1.5 on 2020-11-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0096_auto_20201116_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_category_table_predicate_asverb',
            old_name='t_category_table_id_object',
            new_name='t_category_table_object',
        ),
        migrations.RenameField(
            model_name='t_category_table_predicate_asverb',
            old_name='t_category_table_id_subject',
            new_name='t_category_table_subject',
        ),
    ]
