# Generated by Django 2.1.5 on 2020-11-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0099_auto_20201116_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_conflict_strategy_category_measure',
            old_name='t_conflict_strategy_category_id',
            new_name='t_conflict_strategy_category',
        ),
        migrations.RenameField(
            model_name='t_conflict_strategy_category_measure',
            old_name='t_memorization_package_memory_palace_technique_id',
            new_name='t_memorization_package_memory_palace_technique_foreignkey5',
        ),
        migrations.RenameField(
            model_name='t_conflict_strategy_category_measure',
            old_name='t_memory_palace_type_location_number_id',
            new_name='t_memory_palace_type_location_number',
        ),
    ]
