# Generated by Django 2.1.5 on 2020-11-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0100_auto_20201116_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_memorization_package_memory_palace_technique',
            old_name='t_calendar_id',
            new_name='t_calendar_foreignkey2',
        ),
        migrations.RenameField(
            model_name='t_memorization_package_memory_palace_technique',
            old_name='t_information_item_tobeoperationalized_id',
            new_name='t_information_item_tobeoperationalized_foreignkey',
        ),
        migrations.RenameField(
            model_name='t_memorization_package_memory_palace_technique',
            old_name='t_week_target_id',
            new_name='t_week_target',
        ),
        migrations.RenameField(
            model_name='t_memorization_package_memory_palace_technique',
            old_name='t_workpackage_relevantinformation_tobememorized_id',
            new_name='t_workpackage_relevantinformation_tobememorized',
        ),
    ]
