# Generated by Django 2.1.5 on 2020-11-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0101_auto_20201116_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_memory_palace_type_location',
            old_name='t_memorization_package_memory_palace_technique_id',
            new_name='t_memorization_package_memory_palace_technique',
        ),
        migrations.RenameField(
            model_name='t_memory_palace_type_location',
            old_name='t_memory_palace_type_id',
            new_name='t_memory_palace_type',
        ),
        migrations.RenameField(
            model_name='t_memory_palace_type_location_packageassignment_timeseries',
            old_name='t_memorization_package_memory_palace_technique_id',
            new_name='t_memorization_package_memory_palace_technique',
        ),
        migrations.RenameField(
            model_name='t_memory_palace_type_location_packageassignment_timeseries',
            old_name='t_memory_palace_type_location_id',
            new_name='t_memory_palace_type_location',
        ),
    ]
