# Generated by Django 2.1.5 on 2020-11-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0102_auto_20201116_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_memory_palace_type_location_daytime',
            old_name='t_memory_palace_type_location_id',
            new_name='t_memory_palace_type_location',
        ),
        migrations.RenameField(
            model_name='t_memory_palace_type_location_number',
            old_name='t_memory_palace_type_location_id',
            new_name='t_memory_palace_type_location',
        ),
    ]
