# Generated by Django 2.1.5 on 2020-11-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0103_auto_20201116_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'T_Week_Target'},
        ),
    ]
