# Generated by Django 2.1.5 on 2020-11-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0104_auto_20201116_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'T_Workpackage'},
        ),
    ]
