# Generated by Django 2.1.5 on 2020-11-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0105_auto_20201116_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'T_Workpackage_Relevantinformation_Tobememorized'},
        ),
    ]
