# Generated by Django 2.1.5 on 2020-11-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0106_auto_20201116_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='id_asinteger',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
