# Generated by Django 2.1.5 on 2020-11-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0107_bookinstance_id_asinteger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id_asinteger',
            field=models.IntegerField(default=None),
        ),
    ]
