# Generated by Django 2.1.5 on 2020-11-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0108_auto_20201116_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_workpackage_relevantinformation_tobememorized',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_workpackage_relevantinformation_tobememorized',
        ),
        migrations.RemoveField(
            model_name='t_week_target_or_workpackage_or_relevinf_timeseries',
            name='t_workpackage_relevantinformation_tobememorized',
        ),
    ]
