# Generated by Django 2.1.5 on 2020-11-16 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0109_auto_20201116_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id_asinteger',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
