# Generated by Django 2.1.5 on 2020-11-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0110_auto_20201116_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_workpackage_relevantinformation_tobememorized',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance'),
        ),
        migrations.AddField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_workpackage_relevantinformation_tobememorized',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance'),
        ),
        migrations.AddField(
            model_name='t_week_target_or_workpackage_or_relevinf_timeseries',
            name='t_workpackage_relevantinformation_tobememorized',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance'),
        ),
    ]
