# Generated by Django 2.1.5 on 2020-11-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0111_auto_20201116_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T_Memorization_Package_Memory_Cards_Technique',
            new_name='T_Memorization_Package_Memory_Palace_Or_Cards_Technique',
        ),
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_calendar_foreignkey2',
        ),
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_conflict_strategy_category_measure_foreignkey',
        ),
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_information_item_tobeoperationalized_foreignkey',
        ),
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_memory_palace_type',
        ),
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_week_target',
        ),
        migrations.RemoveField(
            model_name='t_memorization_package_memory_palace_technique',
            name='t_workpackage_relevantinformation_tobememorized',
        ),
        migrations.RemoveField(
            model_name='author',
            name='t_memorization_package_memory_palace_technique_foreignkey',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='t_memorization_package_memory_palace_technique_foreignkey2',
        ),
        migrations.RemoveField(
            model_name='t_calendar',
            name='t_memorization_package_memory_palace_technique_foreignkey4',
        ),
        migrations.RemoveField(
            model_name='t_calendar_conflict_related_association',
            name='t_memorization_package_memory_palace_technique',
        ),
        migrations.RemoveField(
            model_name='t_conflict_strategy_category_measure',
            name='t_memorization_package_memory_palace_technique_foreignkey5',
        ),
        migrations.RemoveField(
            model_name='t_information_item_tobeoperationalized',
            name='t_memorization_package_memory_cards_technique',
        ),
        migrations.RemoveField(
            model_name='t_information_item_tobeoperationalized',
            name='t_memorization_package_memory_palace_technique_foreignkey3',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_type_location',
            name='t_memorization_package_memory_palace_technique',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_type_location_packageassignment_timeseries',
            name='t_memorization_package_memory_palace_technique',
        ),
        migrations.AlterModelTable(
            name='t_memorization_package_memory_palace_or_cards_technique',
            table='t_memorization_package_memory_palace_or_cards_technique',
        ),
        migrations.DeleteModel(
            name='T_Memorization_Package_Memory_Palace_Technique',
        ),
    ]
