# Generated by Django 2.1.5 on 2020-11-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0113_auto_20201119_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_information_item_tobeoperationalized',
            name='t_memorization_package_memory_palace_or_cards_technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Or_Cards_Technique'),
        ),
    ]
