# Generated by Django 2.1.5 on 2020-11-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0114_t_information_item_tobeoperationalized_t_memorization_package_memory_palace_or_cards_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_calendar',
            name='t_memorization_package_memory_palace_or_cards_technique_fk4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Or_Cards_Technique'),
        ),
        migrations.AddField(
            model_name='t_calendar_conflict_related_association',
            name='t_memorization_package_memory_palace_or_cards_technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Or_Cards_Technique'),
        ),
        migrations.AddField(
            model_name='t_conflict_strategy_category_measure',
            name='t_memorization_package_memory_palace_or_cards_technique_fk5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Or_Cards_Technique'),
        ),
        migrations.AddField(
            model_name='t_memory_palace_type_location',
            name='t_memorization_package_memory_palace_or_cards_technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Or_Cards_Technique'),
        ),
        migrations.AddField(
            model_name='t_memory_palace_type_location_packageassignment_timeseries',
            name='t_memorization_package_memory_palace_or_cards_technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memorization_Package_Memory_Palace_Or_Cards_Technique'),
        ),
    ]
