# Generated by Django 2.1.5 on 2020-11-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0115_auto_20201119_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='is_mct_t_information_item_tobeoperationalized',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='is_mpt_t_conflict_strategy_category_measure',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='is_mpt_t_information_item_tobeoperationalized',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='is_mpt_t_week_target',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='is_mpt_t_workpackage_relevantinformation_tobememorized',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
