# Generated by Django 2.1.5 on 2020-11-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0116_auto_20201119_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_memorization_package_memory_palace_or_cards_technique',
            name='t_memory_palace_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Type'),
        ),
    ]
