# Generated by Django 2.1.5 on 2020-11-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0117_t_memorization_package_memory_palace_or_cards_technique_t_memory_palace_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_memorization_package_memory_palace_or_cards_technique',
            options={'ordering': ['memorization_package_title']},
        ),
    ]
