# Generated by Django 2.1.5 on 2020-11-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0119_auto_20201120_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_memory_palace_type_location',
            options={'ordering': ['memory_palace_type_location']},
        ),
    ]
