# Generated by Django 2.1.5 on 2020-11-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0120_auto_20201121_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_memory_palace_type_location_packageassignment_timeseries',
            options={'ordering': ['assignment_to_memorization_package_datetime']},
        ),
    ]
