# Generated by Django 2.1.5 on 2020-11-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0121_auto_20201121_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_memory_palace_type_location_number',
            options={'ordering': ['memory_palace_number']},
        ),
    ]
