# Generated by Django 2.1.5 on 2020-11-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0122_auto_20201121_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_memory_palace_type_location_daytime',
            options={'ordering': ['memory_palace_daytime']},
        ),
    ]
