# Generated by Django 2.1.5 on 2020-11-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0123_auto_20201121_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_calendar_conflict_related_association',
            name='t_calendar_foreignkey',
        ),
        migrations.RemoveField(
            model_name='t_calendar_conflict_related_association',
            name='t_category_table_entry',
        ),
        migrations.RemoveField(
            model_name='t_calendar_conflict_related_association',
            name='t_conflict',
        ),
        migrations.RemoveField(
            model_name='t_calendar_conflict_related_association',
            name='t_memorization_package_memory_palace_or_cards_technique',
        ),
        migrations.RemoveField(
            model_name='t_ausatemmuskulatur_isnot_entspannt_dueto_strategyrefinemt',
            name='t_calendar_conflict_related_association',
        ),
        migrations.RemoveField(
            model_name='t_calendar',
            name='t_calendar_conflict_related_association_foreignkey',
        ),
        migrations.DeleteModel(
            name='T_Calendar_Conflict_Related_Association',
        ),
    ]
