# Generated by Django 2.1.5 on 2020-11-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0124_auto_20201122_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_calendar',
            name='hypothetic_conflict_appointment_association_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='t_calendar',
            name='is_hypothetic_conflict_appointment',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_calendar',
            name='t_category_table_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.t_category_table_entry'),
        ),
        migrations.AddField(
            model_name='t_calendar',
            name='t_conflict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Conflict'),
        ),
    ]
