# Generated by Django 2.1.5 on 2020-11-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0125_auto_20201122_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ausatemmuskulatur_isnot_entspannt_dueto_strategyrefinemt',
            name='t_calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar'),
        ),
    ]
