# Generated by Django 2.1.5 on 2020-11-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0126_t_ausatemmuskulatur_isnot_entspannt_dueto_strategyrefinemt_t_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_ausatemmuskulatur_isnot_entspannt_dueto_strategyrefinemt',
            options={'ordering': ['created_datetime']},
        ),
        migrations.AlterModelOptions(
            name='t_ausatemmuskulatur_strategyrefinement_conflict_phase',
            options={'ordering': ['conflict_phase_name']},
        ),
        migrations.AlterModelOptions(
            name='t_conflict_strategy_category',
            options={'ordering': ['conflict_strategy_category_verb']},
        ),
        migrations.AlterModelOptions(
            name='t_conflict_strategy_category_measure',
            options={'ordering': ['conflict_strategy_category_measure_description']},
        ),
    ]
