# Generated by Django 2.1.5 on 2020-11-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0127_auto_20201122_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_category_table_entry',
            name='t_category_table',
        ),
        migrations.RemoveField(
            model_name='t_calendar',
            name='t_category_table_entry',
        ),
        migrations.RemoveField(
            model_name='t_category_table_predicate_asverb',
            name='t_category_table_object',
        ),
        migrations.RemoveField(
            model_name='t_category_table_predicate_asverb',
            name='t_category_table_subject',
        ),
        migrations.RemoveField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            name='t_category_table',
        ),
        migrations.RemoveField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            name='t_category_table_entry',
        ),
        migrations.DeleteModel(
            name='t_category_table',
        ),
        migrations.DeleteModel(
            name='t_category_table_entry',
        ),
    ]
