# Generated by Django 2.1.5 on 2020-11-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0128_auto_20201122_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Category_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_table_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_category_table',
                'ordering': ['category_table_name'],
            },
        ),
    ]
