# Generated by Django 2.1.5 on 2020-11-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0129_t_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Category_Table_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=255)),
                ('t_category_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table')),
            ],
            options={
                'db_table': 't_category_table_entry',
                'ordering': ['category_name'],
            },
        ),
    ]
