# Generated by Django 2.1.5 on 2020-11-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0130_t_category_table_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_calendar',
            name='t_category_table_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table_Entry'),
        ),
        migrations.AddField(
            model_name='t_category_table_predicate_asverb',
            name='t_category_table_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='T_Category_Table_Related_Name', to='catalog.T_Category_Table'),
        ),
        migrations.AddField(
            model_name='t_category_table_predicate_asverb',
            name='t_category_table_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table'),
        ),
        migrations.AddField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            name='t_category_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table'),
        ),
        migrations.AddField(
            model_name='t_wt_or_wp_or_infotbo_category_timeseries',
            name='t_category_table_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table_Entry'),
        ),
    ]
