# Generated by Django 2.1.5 on 2020-11-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0132_auto_20201122_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_calendar',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_conflict_strategy_category_measure',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_information_item_tobeoperationalized',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_memory_palace_memorization_timeseries_action',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_week_target',
        ),
        migrations.RemoveField(
            model_name='t_memory_palace_memorization_timeseries',
            name='t_workpackage_relevantinformation_tobememorized',
        ),
        migrations.DeleteModel(
            name='T_Memory_Palace_Memorization_Timeseries',
        ),
        migrations.DeleteModel(
            name='T_Memory_Palace_Memorization_Timeseries_Action',
        ),
    ]
