# Generated by Django 2.1.5 on 2020-11-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0133_auto_20201123_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Memory_Palace_Or_Cards_Memorization_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_memorization_package_memory_palace_or_cards_technique_snap', models.IntegerField(default=None, null=True)),
                ('t_memory_palace_type_location_number_snap', models.IntegerField(default=None, null=True)),
                ('action_datetime', models.DateTimeField(blank=True, null=True)),
                ('t_calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar')),
                ('t_conflict_strategy_category_measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Conflict_Strategy_Category_Measure')),
                ('t_information_item_tobeoperationalized', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized')),
            ],
            options={
                'db_table': 't_memory_palace_or_cards_memorization_timeseries',
                'ordering': ['action_datetime'],
            },
        ),
        migrations.CreateModel(
            name='T_Memory_Palace_Or_Cards_Memorization_Timeseries_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 't_memory_palace_or_cards_memorization_timeseries_action',
                'ordering': ['action_description'],
            },
        ),
        migrations.AddField(
            model_name='t_memory_palace_or_cards_memorization_timeseries',
            name='t_memory_palace_or_cards_memorization_timeseries_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Memory_Palace_Or_Cards_Memorization_Timeseries_Action'),
        ),
        migrations.AddField(
            model_name='t_memory_palace_or_cards_memorization_timeseries',
            name='t_week_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author'),
        ),
        migrations.AddField(
            model_name='t_memory_palace_or_cards_memorization_timeseries',
            name='t_workpackage_relevantinformation_tobememorized',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance'),
        ),
    ]
