# Generated by Django 2.1.5 on 2020-11-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0135_auto_20201125_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_day_target_sequence_timeseries',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
