# Generated by Django 2.1.5 on 2020-11-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0136_t_day_target_sequence_timeseries_created_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_day_target_sequence_timeseries',
            options={'ordering': ['created_datetime']},
        ),
    ]
