# Generated by Django 2.1.5 on 2020-11-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0139_t_wt_is_excluded_from_dt_mp_assignment_on_weekday_timeseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_calendar',
            name='t_category_table_entry',
        ),
    ]
