# Generated by Django 2.1.5 on 2020-11-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0141_auto_20201126_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Category_Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('t_calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Calendar')),
                ('t_category_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table')),
                ('t_category_table_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Category_Table_Entry')),
                ('t_conflict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Conflict')),
                ('t_information_item_tobeoperationalized', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.T_Information_Item_Tobeoperationalized')),
                ('t_week_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('t_workpackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
            options={
                'db_table': 't_category_timeseries',
                'ordering': ['created_datetime'],
            },
        ),
    ]
