# Generated by Django 2.1.5 on 2020-11-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0142_t_category_timeseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_week_target_or_workpackage_or_relevinf_timeseries',
            name='t_week_target',
        ),
        migrations.RemoveField(
            model_name='t_week_target_or_workpackage_or_relevinf_timeseries',
            name='t_workpackage',
        ),
        migrations.RemoveField(
            model_name='t_week_target_or_workpackage_or_relevinf_timeseries',
            name='t_workpackage_relevantinformation_tobememorized',
        ),
        migrations.AlterModelOptions(
            name='t_workpackage_actual_duration_timeseries',
            options={'ordering': ['measurement_datetime']},
        ),
        migrations.DeleteModel(
            name='T_Week_Target_Or_Workpackage_Or_Relevinf_Timeseries',
        ),
    ]
