# Generated by Django 2.1.5 on 2020-11-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0143_auto_20201126_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
