# Generated by Django 2.1.5 on 2020-11-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0144_auto_20201126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
