# Generated by Django 2.1.5 on 2020-11-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0146_auto_20201126_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['created_datetime'], 'verbose_name': 'T_Week_Target'},
        ),
    ]
