# Generated by Django 2.1.5 on 2020-11-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0147_auto_20201126_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='associated_email_subject',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
