# Generated by Django 2.1.5 on 2020-11-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0148_auto_20201126_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created_datetime'], 'verbose_name': 'T_Workpackage'},
        ),
    ]
